### ISSUE TITLE
Vector operators don't seem to work

### ISSUE THREAD

**Issue by rosshadden** [pragmagic/godot-nim#13]
It's hard to tell which of them aren't working, but for example this:

```nim
print vec2(1, 0) + vec2(0, 1)
```

prints `1, 0`, whereas if I define my own `+` method:

```nim
proc `+`(a, b: Vector2): Vector2 = vec2(a.x + b.x, a.y + b.y)
print vec2(1, 0) + vec2(0, 1)
```

it prints `1, 1` as expected.

Also using `+=` gives me a stack overflow and crashes, but maybe I'm not using it correctly:

```nim
var a = vec2(1, 0)
var b = vec2(0, 1)
a += b
print a
```

Thus I have to resort to using `a = a + b` instead, which only works with my `+` override above. I am unable to create a corresponding `+=` override because I get "`a.x` cannot be assign to".

**Comment by endragor** [comment]
I've fixed `+=`, but cannot reproduce the `+` problem. All of these print `1, 1` for me:
```
let v = vec2(1, 0) + vec2(0, 1)
    print v
    print vec2(1, 0) + vec2(0, 1)

    var a = vec2(1, 0)
    var b = vec2(0, 1)
    a += b
    print a
```

**Comment by rosshadden** [comment]
I copy/pasted your code block above and got three occurrences of `1, 0` printed.

Godot: master, specifically `0a691bf29`
OS: Arch Linux

Nim:

```
Nim Compiler Version 0.17.3 [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: b7e69e7cbbf6139316841bcc7c596e93ac78d994
active boot switches: -d:release -d:nativeStackTrace
```

My Nim version is outdated by about a week, so I'll try updating it.

**Comment by rosshadden** [comment]
It got more strange. `-` and `-=` actually work great. Which now that I think about it isn't really as crazy as I first thought, since they call different gdnative functions, but still weird.

**Comment by endragor** [comment]
@rosshadden is this still relevant to you? Could you check if you get the same behaviour with C bindings when you use addition of vectors?

**Comment by rosshadden** [comment]
Yes, I still get the same behavior when using vector addition. I know you can't recreate it---is there anything I can do to help figure out what's going on?

**Comment by endragor** [comment]
@rosshadden Yes, as I mentioned - can you try seeing if you get the same behaviour with C bindings, when invoking GDNative API directly?

**Comment by rosshadden** [comment]
Oh, I misunderstood you. I'll try when I get a chance.

**Comment by rosshadden** [comment]
I apologize, but I don't know how I can test with C bindings.

I tried getting the C++ bindings to work, but I ran into build errors just trying to compile them.  I also tried the godot-python bindings, just to see if another library using the same gdnative `vector2OperatorAdd` method works, and it did work.  I'm not sure what that means, but my understanding is the behavior should be consistent for all libraries that call the same gdnative API methods, so this surprised me.

**Comment by endragor** [comment]
I implemented Vector2 operations fully within the library, so this should not longer be an issue. I wonder if similar problems exist with other operations though. I never experienced anything similar and couldn't reproduce this, as you know.

**Comment by endragor** [comment]
Closing this. Let me know if something similar happens with other procedures.
